version: '3'

services:
    django:
        build:
          context: .
          args:
            - DEV=true
        command: >
          sh -c "python manage.py wait_for_db &&
                 python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:8000"
        ports:
          - "8000:8000"
        volumes:
          - ./django_api:/home/app/django_api
        depends_on:
          - db
        env_file:
          - ./.env.dev

    db:
        image: postgres:15-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        env_file:
          - ./.env.dev

volumes:
  postgres_data: