version: '3'

services:
    django:
        build: .
        ports:
          - "8000:8000"
        depends_on:
          - db
        env_file:
          - ./.env.dev

    db:
        image: postgres:15-alpine
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        env_file:
          - ./.env.dev

volumes:
  postgres_data: